---
- name: debug
  debug:
    msg: "Jeste Haproxe"
- block:
    - name: install haproxy
      yum:
        name:
          - haproxy

    - name: install policycoreutils
      yum:
        name: policycoreutils-python
      when: ansible_distribution_major_version == "7"

    - name: install policycoreutils
      yum:
        name: policycoreutils-python-utils
      when: ansible_distribution_major_version == "8"
  become: true
  become_user: root

- block:
    - name: create dirs 1
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      loop:
        - "{{ app.value.haproxy.user.home }}/haproxy"
        - "{{ app.value.haproxy.user.home }}/haproxy/conf"
        - "{{ app.value.haproxy.user.home }}/haproxy/var"
    - name: create dirs 2
      file:
        path: "{{ item }}"
        state: directory
        setype: var_run_t
        mode: 0755
      loop:
        - "{{ app.value.haproxy.user.home }}/haproxy/run"
    - name: copy haproxy config
      template:
        src: haproxy.cfg
        dest: "{{ app.value.haproxy.user.home }}/haproxy/conf/haproxy.cfg"
        setype: etc_t
        validate: haproxy -c -f %s
        mode: 0640
        owner: "{{ app.value.haproxy.user.user }}"
      notify:
        - restart haproxy
      become_user: root # TODO need to find out why it has to be root + owner instead of become_user: haproxy

  become: true
  become_user: "{{ app.value.haproxy.user.user }}"
- block:
    - name: copy haproxy service
      template:
        src: haproxy.service
        dest: "/etc/systemd/system/{{ app.value.haproxy.user.user }}-haproxy-{{ app.key }}.service"
        mode: 0644
      notify:
        - restart haproxy
    - name: add listening ports to selinux
      seport:
        ports: "{{ item }}"
        proto: tcp
        setype: http_port_t
        state: present
      loop: '{{ app.value.haproxy.proxies|json_query("*.port") }}'
    - name: add destination ports to selinux
      seport:
        ports: "{{ item.split(':')[1] }}"
        proto: tcp
        setype: http_port_t
        state: present
      loop: '{{ app.value.haproxy.proxies|json_query("*.servers[]") }}'

    - meta: flush_handlers
    - name: start haproxy
      systemd:
        name: "{{ app.value.haproxy.user.user }}-haproxy-{{ app.key }}.service"
        state: started
        enabled: true
        daemon_reload: true
  become: true
  become_user: root
